spring:
  sql:
    init:
      mode: always
  datasource:
    postgres:
      hikari:
        jdbc-url: jdbc:postgresql://localhost:5432/book-app?currentSchema=public
        username: postgres
        password: admin
        driver-class-name: org.postgresql.Driver
        auto-commit: false
        minimum-idle: 10
        maximum-pool-size: 10
mybatis:
  configuration:
    map-underscore-to-camel-case: true
jwt:
  accesstoken:
    secretkey: Dp/^po=<bbbTv&<Xg%&kL#8I3sg9|u
    expirationtime: 300000
  refreshtoken:
    expirationtime: 900000
server:
  port: ${PORT:8080}
