spring:
  sql:
    init:
      mode: always
  datasource:
    neo4j:
      hikari:
        jdbc-url: jdbc:neo4j:bolt://localhost:7687
        username: neo4j
        password: q6T3sw1bII1XmL569fRNm-YUCubj-hEF2VCIecyekHM
        driver-class-name: org.neo4j.jdbc.bolt.BoltDriver
        database: movie-graph
    postgres:
      hikari:
        jdbc-url: jdbc:postgresql://localhost:5432/fmh?currentSchema=public
        username: postgres
        password: admin
        driver-class-name: org.postgresql.Driver
        auto-commit: false
        minimum-idle: 10
        maximum-pool-size: 10
mybatis:
  configuration:
    map-underscore-to-camel-case: true
server:
  port: ${PORT:8080}
